# Generated by Django 3.2.9 on 2021-12-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'таг',
                'verbose_name_plural': 'теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название поста')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('title_i', models.ImageField(upload_to='post/title/%Y/%m/%d', verbose_name='Титульное изображение')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.tag', verbose_name='таг')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['datetime_create'],
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/imaage/%Y/%m/%d', verbose_name='Путь хранения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
